# Generated by Django 5.1.2 on 2024-12-17 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lab4', '0003_alter_customer_name_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
